### PR TITLE
Consume SIL dependencies as nuget package instead of TC artifacts

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/pdfdroplet/24)

### CODE REVIEW

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/pdfdroplet/24)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[src/PdfDroplet.csproj, line 57 at r1](https://reviewable.io/reviews/sillsdev/pdfdroplet/24#-MODwQ8CCAyXZxv5WUO5:-MODwQ8CCAyXZxv5WUO6:b-oiygl8) ([raw file](https://github.com/sillsdev/pdfdroplet/blob/5b5863596c1810daa4c59e5ac58ffc68f5e1971a/src/PdfDroplet.csproj#L57)):*
> ```XML
>     </Reference>
>     <Reference Include="L10NSharp">
>       <HintPath>..\lib\L10NSharp.dll</HintPath>
> ```

Future changes will be:
1) Modify Teamcity build to remove these dependencies.
2) Re-generate (or clean-up) buildupdate.*.sh scripts to not download these dependencies.
3) Publish a nuget package probably

**Review by ermshiperete — APPROVED** [review]

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/pdfdroplet/24)* status: all files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/packages.config, line 26 at r1](https://reviewable.io/reviews/sillsdev/pdfdroplet/24#-MOHI58Z2deqJq851DDf:-MOHI58Z2deqJq851DDg:btfy8dy) ([raw file](https://github.com/sillsdev/pdfdroplet/blob/21edafe3bfe2699824083a15decb44b7a02c5f32/src/packages.config#L26)):*
>   &lt;package id="SIL.WritingSystems" version="8.0.0-beta0239" targetFramework="net461" /&gt;

Why do we need this? I don't see it as a current TC dep.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/pdfdroplet/24)* status: all files reviewed, 1 unresolved discussion

___
*[src/packages.config, line 26 at r1](https://reviewable.io/reviews/sillsdev/pdfdroplet/24#-MOHI58Z2deqJq851DDf:-MOHJfNM23VXJot81NIY:b-ffq2i2) ([raw file](https://github.com/sillsdev/pdfdroplet/blob/21edafe3bfe2699824083a15decb44b7a02c5f32/src/packages.config#L26)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

>   &lt;package id="SIL.WritingSystems" version="8.0.0-beta0239" targetFramework="net461" /&gt;

Why do we need this? I don't see it as a current TC dep.
</blockquote></details>

Never mind. I see SI.Windows.Forms depends on it. Surprising.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/pdfdroplet/24)* status: all files reviewed, 1 unresolved discussion

___
*[src/packages.config, line 26 at r1](https://reviewable.io/reviews/sillsdev/pdfdroplet/24#-MOHI58Z2deqJq851DDf:-MOHOMY32ZKjyU834rVc:b-tnxid1) ([raw file](https://github.com/sillsdev/pdfdroplet/blob/21edafe3bfe2699824083a15decb44b7a02c5f32/src/packages.config#L26)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Never mind. I see SI.Windows.Forms depends on it. Surprising.
</blockquote></details>

Yes, Nuget lists SIL.Windows.Forms as requiring i.

**Pull request merged**
