### PR TITLE
Update PdfDroplet to VS 2022 SDK project and latest libpalaso

### PR DESCRIPTION
**Pull request by StephenMcConnel**
I've built this on both Windows and Linux.  I won't claim to have tested it extensively, but I did test the gui program on Windows a bit.  This is needed for compatibility with the alpha build of Bloom which has upgraded to SIL.Core 14.2.0-beta0019 (with other libpalaso assemblies also updated, of course).  Bloom uses PdfDroplet in its PDF publishing process, and incompatible libpalaso versions can be a showstopper.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/pdfdroplet/31)

### CODE REVIEW

**Review by andrew-polk — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/pdfdroplet/31)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/pdfdroplet/31)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/app.config` line 42 at r1](https://reviewable.io/reviews/sillsdev/pdfdroplet/31#-O3cuyxl9FH3vcphpfx6:-O3cuyxl9FH3vcphpfx7:b-112g3y) ([raw file](https://github.com/sillsdev/pdfdroplet/blob/048364a0e7cb4f3f119e34af7d7dd0789631d395/src/app.config#L42)):*
> ```
>       <dependentAssembly>
>         <assemblyIdentity name="SIL.Core" publicKeyToken="cab3c8c5232dfcf2" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
> ```

I would have expected these 10.0s to change to 14.0s for SIL.Core*

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/pdfdroplet/31)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/app.config` line 42 at r1](https://reviewable.io/reviews/sillsdev/pdfdroplet/31#-O3cuyxl9FH3vcphpfx6:-O3dVwUa1Iwu1fqV2ZmQ:b-896fix) ([raw file](https://github.com/sillsdev/pdfdroplet/blob/048364a0e7cb4f3f119e34af7d7dd0789631d395/src/app.config#L42)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I would have expected these 10.0s to change to 14.0s for SIL.Core*
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/pdfdroplet/31)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
